[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.128.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

# URL normalization redirects
[[redirects]]
  from = "/products"
  to = "/products/"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/faq"
  to = "/faq/"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/papi"
  to = "/papi/"
  status = 301
